using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace ProyectoDIV1.Views
{
    /// <summary>
    /// Interaction logic for inicio.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class inicioDiseno : ContentPage
    {
        public inicioDiseno()
        {
            InitializeComponent();
        }
    }
}
	