using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace ProyectoDIV1.Views
{
    /// <summary>
    /// Interaction logic for inicio.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class inicioPortada : ContentPage
    {
        public inicioPortada()
        {
            InitializeComponent();
            IrAinicio();
        }

        private async void IrAinicio()
        {
            await Task.Delay(2000);
            await Application.Current.MainPage.Navigation.PushAsync(new inicio());
        }
    }
}
	